### ISSUE TITLE
Instructor Feedback Week 15

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [navy2319/MyProject#2]
Hi Naivi! I'm really looking forward to seeing Shep's Little Acres website in action next week!  Following are a few comments and things to focus on as you do your last push on this project:
- [x] First, are you remembering to add files, commit and push? There have not been any updates in github in a month, yet I know you've been making progress based on our daily scrums.  Please add, commit and push as soon as possible, and let me know when that is done so I can provide better feedback before next week.
- [x] Readme.md: be sure to update for your current design, including your independent research topic. Also be sure to add links to your design docs.
- [x] Project plan, journal/time log started off strong, but there hasn't been a push in a while so I'm not sure how progress has gone since 4/5.
- [x] Consider adding a .gitignore file to limit what is synced to git. It's not recommended to have the .iml, .idea and out directory in version control.

**Comment by navy2319** [comment]
Thanks Paula, I added the .gitignore file and also I wasn't pushing anything because im having problems with my tests not passing and I thought it would of be better to get them to work before pushing but their not working yet so I started to push again.
